# === the basics ===
title: kamila.is
permalinks: pretty
repository: anotherkamila/kamila.is

# === defaults ===
defaults:
  - scope: {path: ""}
    values:
      layout: default

# === Build settings ===
exclude: [Gemfile, Gemfile.lock]
