# === the basics ===
title: kamila.is
url: ""
permalink: pretty

# === defaults ===
defaults:
  - scope: {path: ""}
    values:
      layout: default

# === Build settings ===
markdown: kramdown
kramdown:
  smartypants: true
gems: [bootstrap, autoprefixer-rails, jekyll-assets]
sass:
    sass_dir: _sass
exclude: [Gemfile, Gemfile.lock]
