# === the basics ===
title: kamila.is
url: "" # the base hostname & protocol for your site
add_to_nav:
  # - [/busy, 'Calendar']
permalinks: pretty

# === defaults ===
defaults:
  - scope: {path: ""}
    values:
      layout: "default"

# === Build settings ===
gems: [bootstrap, autoprefixer-rails, jekyll-assets]
sass:
    sass_dir: _sass
exclude: [Gemfile, Gemfile.lock]
