# === the basics ===
title: kamila.is
email: kamila@ksp.sk
permalink: pretty
repository: anotherkamila/kamila.is
github_username:  anotherkamila
twitter_username: anotherkamila

# === defaults ===
defaults:
  - scope: {path: ""}
    values:
      layout: default

# === Build settings ===
excerpt_separator: <!--more-->
exclude: [Gemfile, Gemfile.lock]
plugins:
  - jekyll-sitemap
