# === the basics ===
title: kamila.is
email: kamila@ksp.sk
permalink: pretty
permalink: /:categories/:title/
repository: anotherkamila/kamila.is
github_username:  anotherkamila
twitter_username: anotherkamila

# === defaults ===
defaults:
  - scope: {path: ""}
    values:
      layout: default
  - scope: {path: "teaching"}
    values:
      layout: tocpost
  - scope: {path: "learning"}
    values:
      layout: tocpost

# === Build settings ===
excerpt_separator: <!--more-->
exclude: [Gemfile, Gemfile.lock]
include:
  - .well-known
plugins:
  - jekyll-sitemap
