title: kamila.is
url: "" # the base hostname & protocol for your site
add_to_nav:
  # - [/busy, 'Calendar']
permalinks: pretty

# Build settings
gems: [bootstrap, autoprefixer-rails, jekyll-assets]
sass:
    sass_dir: _sass
exclude: [bin, Gemfile, Gemfile.lock, vendor]

